### ISSUE TITLE
case_new - A new case is created -> Notify the Assignee

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/sns2email#1]
When a new case is created, we need to inform the person who is assigned to that case.
Notification type = `case_new`
The JSON payload:

{"notification_type": "case_new"
, "bz_source_table": "ut_notification_case_new"
, "notification_id": "ut_notification_case_new-xxx"
, "created_datetime" : "the timestamp when this was done ex: 2018-06-12 09:21:08"
, "unit_id" : "unit_id (the BZ id for the unit)"
, "case_id" : "case_id (the BZ case id)"
, "case_title" : "case_title (the title of the case)"
, "reporter_user_id" : "reporter_user_id (the BZ user id of the user who created the case)"
, "assignee_user_id" : "assignee_user_id (the BZ user id for the assignee)"}
What we need to do:

Send an email notification to the "assignee_user_id" to inform him/her that he/she has been assigned to this new case.
# Unsubscribe:
- We need to allow the user to unsubscribe from this type of notification (`case_new`) if he/she chooses to.
- When a user has decided to unsubscribe, we should NOT send this user more notification if the notification type is `case_new`

**Comment by franck-boullier** [comment]
Housekeeping - splitting this issue in 3 different issues

**Comment by kaihendry** [comment]
https://github.com/unee-t/lambda2sns/blob/master/tests/events/case_new.json
