### ISSUE TITLE
case_user_invited - A New user is invited to a case -> Notify the invited user

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/sns2email#3]
When a new user is invited to a case we need to inform the person who is invited to that case.
Notification type = `case_user_invited`

# The JSON payload:
{"notification_type": "case_user_invited"
, "bz_source_table": "ut_notification_case_invited"
, "notification_id": "ut_notification_case_invited-xxx"
, "created_datetime" : "the timestamp when this was done ex: 2018-06-12 09:21:08"
, "unit_id" : "unit_id (the BZ id for the unit)"
, "case_id" : "case_id (the BZ case id)"
, "case_title" : "case_title (the title of the case)"
, "invitee_user_id" : "invitee_user_id (the BZ user id for the invited user)"}

# What we need to do:
Send an email notification to the "invitee_user_id" to inform him/her that he/she has been invited to this new case.

# Unsubscribe:
- We need to allow the user to unsubscribe from this type of notification (`case_user_invited`) if he/she chooses to.
- When a user has decided to unsubscribe, we should NOT send this user more notification if the notification type is `case_user_invited`

**Comment by kaihendry** [comment]
https://github.com/unee-t/lambda2sns/blob/master/tests/events/case_user_invited.json

**Comment by kaihendry** [comment]
How do I know *who* invited **invitee_user_id** ?

**Comment by franck-boullier** [comment]
At this point we can't retrieve that information -> we omit that info
